version: '3.3'
services:
  backend:
    image: dto80/se234-lab12
    ports:
      - 8082:8080
    volumes:
      - tupe: bind
      - source: /home/ubuntu/Data
      - target: /data.xlsx
  frontend:
    image: jjkung/lab12
    ports:
      - 8081:80
